# Generated by Django 5.0.4 on 2024-08-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='astronaut',
            new_name='astronauts',
        ),
        migrations.RenameField(
            model_name='spacecraft',
            old_name='maufacturer',
            new_name='manufacturer',
        ),
    ]
