# Generated by Django 5.0.4 on 2024-07-07 17:50
import random
from django.db import migrations


def add_barcorde(apps, schema_editor):
    product_model = apps.get_model('main_app', 'Product')
    all_products = product_model.objects.all()
    
    all_barcodes = random.sample(
        range(100000000, 999999999),
        len(all_products)
    )
    
    for i in range(len(all_products)):
        curr_product = all_products[i]
        curr_product.barcode = all_barcodes[i]
        curr_product.save()


def reverse_add_barcode(apps, schema_editor):
    product_model = apps.get_model('main_app', 'Product')
    
    for product in product_model.objects.all():
        product.barcode = 0
        product.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_barcorde, reverse_add_barcode)
    ]
