# Generated by Django 5.0.4 on 2024-07-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zoodisplayanimals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZooDisplayAnimals',
            new_name='ZooDisplayAnimal',
        ),
    ]
