# Generated by Django 5.0.4 on 2024-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
