# Generated by Django 5.0.4 on 2024-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_menureview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menureview',
            options={'verbose_name': 'Menu Review', 'verbose_name_plural': 'Menu Reviews'},
        ),
        migrations.AlterModelOptions(
            name='regularrestaurantreview',
            options={'verbose_name': 'Restaurant Review', 'verbose_name_plural': 'Restaurant Reviews'},
        ),
    ]
